name: stripe_example
description: Demonstrates how to use the stripe plugin.

publish_to: 'none'

environment:
  sdk: '>=2.10.0 <3.0.0'
  flutter: '>=1.22.4'

dependencies:
  flutter:
    sdk: flutter

  flutter_stripe:
    git:
      url: git://github.com/risdeit/flutter_stripe.git
      path: packages/stripe
      ref: main

  pay:
    git:
      url: git://github.com/risdeit/flutter-plugin
      path: pay
      ref: main

  http: ^0.13.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
  fonts:
    - family: OtomanopeeOne
      fonts:
        - asset: fonts/OtomanopeeOne.ttf