name: stripe_ios
description: Stripe platform implementation for iOS
version: 1.3.0
repository: https://github.com/flutter-stripe/flutter_stripe
homepage: https://pub.dev/packages/flutter_stripe

environment:
  sdk: '>=2.10.0 <3.0.0'
  flutter: '>=1.22.4'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
   plugin:
    platforms:
      ios:
        pluginClass: StripeIosPlugin