name: stripe_platform_interface
description: Platform interface for stripe sdk
version: 1.3.0
repository: https://github.com/flutter-stripe/flutter_stripe
homepage: https://pub.dev/packages/flutter_stripe

environment:
  sdk: '>=2.10.0 <3.0.0'
  flutter: '>=1.22.4'

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^0.12.0
  json_annotation: ^3.0.1
  meta: ^1.3.0-nullsafety.3
  plugin_platform_interface: ^1.0.3

dev_dependencies:
  build_runner: ^1.8.1
  flutter_test:
    sdk: flutter
  freezed: ^0.12.7
  json_serializable: ^3.2.3
