name: flutter_stripe
description: Flutter library for Stripe. Supports PaymentSheets, Apple & Google Pay, SCA, PSD2 and much more.
version: 1.3.0
homepage: https://github.com/flutter-stripe/flutter_stripe
repository: https://github.com/flutter-stripe/flutter_stripe

environment:
  sdk: '>=2.10.0 <3.0.0'
  flutter: '>=1.22.4'

dependencies:
  flutter:
    sdk: flutter

  stripe_android:
    git:
      url: git://github.com/risdeit/flutter_stripe.git
      path: packages/stripe_android
      ref: main

  stripe_ios:
    git:
      url: git://github.com/risdeit/flutter_stripe.git
      path: packages/stripe_ios
      ref: main

  stripe_platform_interface:
    git:
      url: git://github.com/risdeit/flutter_stripe.git
      path: packages/stripe_platform_interface
      ref: main

dev_dependencies:
  flutter_test:
    sdk: flutter



